# Set of default parameters for steady Navier-Stokes
mesh:       './meshes/cavity2d_h0.05.h5'    # in path ./meshes/
rho:        1.0
mu:         0.035

boundary_conditions: 
    - id: 1
      preset: 'driven_lid'
      type: 'dirichlet'
      method: 'essential'
      value: 
          # R: 1.0
          U: 35
    - id: 2
      preset: 'noslip'
      value: [0., 0.]
      method: 'essential'
    # - id: 3
    #   preset: 'navierslip'    # probably best way: split boundary in gmsh and
    #                         # set a number of individual slip bcs
    #   value:
    #       gm: 1.
    #       R: 1.
    #       dR: 0.1
      # preset: 'navierslip': take Poiseuille gamma*value, R
      # type: 'navierslip': raw values
      

# solver setup
elements:   'Mini'
use_temam:  True
backflowstab:
    outlet: True
    nitsche: 0    # (nitsche bnds) 0: None, 1: (u.n), 2: |u.n|_
fix_pressure: True
fix_pressure_point: [0., 0.]
nitsche: 
    method: 0      # 0: skew-symmetric, 1: positive
    beta1: 100
    beta2: 0.3

nonlinear:
    method: 'picard'
    maxit: 100
    init_steps: 5
    use_aitken: 1   #  0: False, 1: Picard only, 2: all
    report: 2       # 0: None, 1: residuals, 2: residuals and energy (inflow/driving/forcing via ESSENTIAL Dbcs!)
    atol: 1.e-13    # note: dot required!!
    rtol: 1.e-16
    stol: 0.0

linear:
    method: 'mumps'


    
    
